# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'PFXAppStore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PFXAppStore
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod "RxCoreData"
  pod 'SwiftLint'
  pod 'SwiftMessages'
  pod 'Hero'
  pod 'lottie-ios'

  target 'PFXAppStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PFXAppStoreEventTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PFXAppStoreProviderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PFXAppStoreCoreDataTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PFXAppStoreUITests' do
    # Pods for testing
  end

end
